In [59]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
import seaborn as sns

In [60]:
df1 = pd.read_csv("central_mumbai.csv")
df2 = pd.read_csv("Navi_mumbai.csv")
df3 = pd.read_csv("south_mumbai.csv")
df4 = pd.read_csv("Thane_data.csv")

In [61]:
# df = pd.concat([df1,df2,df3,df4], ignore_index=True)
# df.to_csv("combined_data")

In [62]:
df = pd.read_csv("combined_data.csv")
df.drop(columns="Unnamed: 0", inplace=True)
display(df.head())

,id,listing_type,title,property_name,project,location,price,price_per_sqft,area,area_unit,...,possession,highlights,nearby,description,builder,posted_by,image,url,configurations,source_page
0,433815,PROJECT,Isle of Calm by GHP Group,Isle of Calm by GHP Group,NaN,"Powai, Mumbai",₹1.33 - 1.61 Cr | ₹1.65 - 2.5 Cr | ₹3.98 Cr,NaN,NaN,NaN,...,NaN,NaN,Chiranjeevi Hospital | Oberoi Mall,"Isle of Calm by GHP Group, one of the known ho...",GHP Group,NaN,NaN,https://www.99acres.com/isle-of-calm-by-ghp-gr...,1 BHK Apartment: ₹1.33 - 1.61 Cr | 2 BHK Apart...,1
1,446564,PROJECT,Nahars Chandi Valley,Nahars Chandi Valley,NaN,"Chandivali, Mumbai",₹3.84 - 6.71 Cr | ₹8.95 Cr,NaN,NaN,NaN,...,NaN,NaN,SM Shetty School | L&T Business Park,"Here are beautifully built 3,4 BHK apartments ...",Nahar Group,NaN,NaN,https://www.99acres.com/nahars-chandi-valley-c...,3 BHK Apartment: ₹3.84 - 6.71 Cr | 4 BHK Apart...,1
2,415161,PROJECT,Hiranandani Empress Hill,Hiranandani Empress Hill,NaN,"Hiranandani Gardens Powai, Mumbai",₹6.73 - 10.28 Cr | ₹10.4 - 10.5 Cr,NaN,NaN,NaN,...,NaN,NaN,Spectra building | Hiranandani Foundation School,"Looking for your dream home? Explore 3,4 BHK a...",Hiranandani Developers,NaN,NaN,https://www.99acres.com/hiranandani-empress-hi...,3 BHK Apartment: ₹6.73 - 10.28 Cr | 4 BHK Apar...,1
3,387255,PROJECT,L&T Elixir Reserve,L&T Elixir Reserve,NaN,"Powai, Mumbai",₹3.85 - 3.9 Cr | ₹5.73 - 6.9 Cr,NaN,NaN,NaN,...,NaN,NaN,A. M. Naik School | The Westin Hotel Mumbai Po...,"Finest 2,3 BHK apartments in Powai available f...",L and T Realty,NaN,NaN,https://www.99acres.com/l-t-elixir-reserve-pow...,2 BHK Apartment: ₹3.85 - 3.9 Cr | 3 BHK Apartm...,1
4,D93324318,PROPERTY,"2 BHK Flat in Chandivali, Mumbai","2 BHK Flat in Chandivali, Mumbai",Godrej Urban Park,"Chandivali, Mumbai",₹2.35 Cr,"₹37,183 /sqft",632 sqft,(59 sqm),...,Ready To Move,8th out of 15 Floors | Centrally Air Conditioned,NaN,This well-Designed 2 bhk apartment in godrej u...,Owner,Yesterday,NaN,https://www.99acres.com/2-bhk-bedroom-apartmen...,NaN,1

In [63]:
df.shape

(6224, 23)

In [64]:
df.info()
df.describe()

<class 'pandas.DataFrame'>
RangeIndex: 6224 entries, 0 to 6223
Data columns (total 23 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              6224 non-null   str
 1   listing_type    6224 non-null   str
 2   title           6224 non-null   str
 3   property_name   6224 non-null   str
 4   project         5837 non-null   str
 5   location        6224 non-null   str
 6   price           6224 non-null   str
 7   price_per_sqft  5870 non-null   str
 8   area            5871 non-null   str
 9   area_unit       5871 non-null   str
 10  area_type       5871 non-null   str
 11  bhk             6224 non-null   str
 12  bathrooms       5831 non-null   float64
 13  possession      5871 non-null   str
 14  highlights      5786 non-null   str
 15  nearby          328 non-null    str
 16  description     6223 non-null   str
 17  builder         6220 non-null   str
 18  posted_by       3812 non-null   str
 19  image           17 non-null     str
 20  url             6224 non-null   str
 21  configurations  353 non-null    str
 22  source_page     6224 non-null   int64
dtypes: float64(1), int64(1), str(21)
memory usage: 5.5 MB

         bathrooms  source_page
count  5831.000000  6224.000000
mean      2.480364     9.004981
std       0.931763     5.571888
min       1.000000     1.000000
25%       2.000000     4.000000
50%       2.000000     8.000000
75%       3.000000    14.000000
max       8.000000    20.000000

In [65]:
df.isnull().sum()

id                   0
listing_type         0
title                0
property_name        0
project            387
location             0
price                0
price_per_sqft     354
area               353
area_unit          353
area_type          353
bhk                  0
bathrooms          393
possession         353
highlights         438
nearby            5896
description          1
builder              4
posted_by         2412
image             6207
url                  0
configurations    5871
source_page          0
dtype: int64

- drop columns: nearby, posted_by, image, congfigurations

In [66]:
drop_cols = [
    "id",
    "listing_type",
    "project",
    "nearby",
    "image",
    "url",
    "source_page",
    'configurations'
    
]

df.drop(columns=drop_cols, inplace=True)

In [67]:
df.duplicated().sum()

np.int64(0)

In [68]:
convert_to_sting = df.select_dtypes(include="object").columns
df[convert_to_sting] = df[convert_to_sting].astype("string")
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 6224 entries, 0 to 6223
Data columns (total 15 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   title           6224 non-null   string
 1   property_name   6224 non-null   string
 2   location        6224 non-null   string
 3   price           6224 non-null   string
 4   price_per_sqft  5870 non-null   string
 5   area            5871 non-null   string
 6   area_unit       5871 non-null   string
 7   area_type       5871 non-null   string
 8   bhk             6224 non-null   string
 9   bathrooms       5831 non-null   float64
 10  possession      5871 non-null   string
 11  highlights      5786 non-null   string
 12  description     6223 non-null   string
 13  builder         6220 non-null   string
 14  posted_by       3812 non-null   string
dtypes: float64(1), string(14)
memory usage: 4.1 MB

C:\Users\HP\AppData\Local\Temp\ipykernel_6212\2559648219.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  convert_to_sting = df.select_dtypes(include="object").columns

In [69]:
df[df["price"].str.contains("L|Lakh|Cr", case=False, na=False)]["price"].head(30)
df[df["price"].str.contains("-", na=False)]["price"].head(20)

0            ₹1.33 - 1.61 Cr | ₹1.65 - 2.5 Cr | ₹3.98 Cr
1                             ₹3.84 - 6.71 Cr | ₹8.95 Cr
2                     ₹6.73 - 10.28 Cr | ₹10.4 - 10.5 Cr
3                        ₹3.85 - 3.9 Cr | ₹5.73 - 6.9 Cr
6      ₹3.42 - 3.86 Cr | ₹4.22 - 5.79 Cr | ₹6.31 - 7....
10           ₹1.84 Cr | ₹2.6 - 2.79 Cr | ₹3.98 - 3.99 Cr
14                     ₹1.27 - 1.35 Cr | ₹1.84 - 2.39 Cr
17                                     ₹12.97 - 14.59 Cr
21                  ₹1.2 - 1.21 Cr | ₹2.09 Cr | ₹2.05 Cr
27     ₹1.96 - 1.98 Cr | ₹2.94 - 3.22 Cr | ₹4.06 - 4....
33           ₹3.06 - 3.78 Cr | ₹3.95 - 6.5 Cr | ₹6.46 Cr
47                            ₹1.15 Cr | ₹1.48 - 1.63 Cr
259                 ₹1.95 Cr | ₹3.5 Cr | ₹8.6 - 12.01 Cr
478    ₹1.06 - 1.86 Cr | ₹1.43 - 2.16 Cr | ₹2.32 - 2....
479    ₹1.12 - 1.75 Cr | ₹1.52 - 2.29 Cr | ₹2.41 - 3....
480                ₹3.73 Cr | ₹3.69 - 5.19 Cr | ₹70.95 L
481           ₹1.7 - 2.01 Cr | ₹2.62 Cr | ₹1.5 - 1.56 Cr
485         ₹1.17 - 1.19 Cr | ₹1.74 - 1.84 Cr | ₹3.04 Cr
487    ₹1.55 - 1.98 Cr | ₹1.06 - 24.44 Cr | ₹2.17 - 3...
489    ₹1.34 - 1.37 Cr | ₹1.67 - 2.26 Cr | ₹2.62 - 2....
Name: price, dtype: string

In [70]:
df= df[~df['price'].str.contains(r"-|\|",na=False)].copy()
df.shape

(5900, 15)

In [71]:
def convert_price(values):
    if pd.isna(values):
        return np.nan
    
    values = str(values).strip().lower()
    values = values.replace("₹", "").replace(",", "").strip()
    
    if "cr" in values:
        values = values.replace("cr", "").strip()
        return float(values) * 10_000_000
    
    elif "lac" in values or "lakh" in values or "l" in values:
        values = (
            values.replace("lakh", "")
                  .replace("lac", "")
                  .replace("l", "")
                  .strip()
        )
        return float(values) * 100_000
    
    try:
        return float(values)
    except ValueError:
        return np.nan
    
df["price"] = df["price"].apply(convert_price)

In [72]:
def convert_price_per_sqft(value):
    if pd.isna(value):
        return np.nan

    value = str(value).strip().lower()
    value = value.replace("₹", "").replace(",", "").strip()

    if "l" in value and "/sqm" in value:
        value = value.replace("l", "").replace("/sqm", "").strip()
        return float(value) * 100_000

    elif "l" in value and "/sqft" in value:
        value = value.replace("l", "").replace("/sqft", "").strip()
        return float(value) * 100_000

    elif "/sqft" in value:
        value = value.replace("/sqft", "").strip()
        return float(value)

    elif "/sqm" in value:
        value = value.replace("/sqm", "").strip()
        return float(value)

    return np.nan

df["price_per_sqft"] = df["price_per_sqft"].apply(convert_price_per_sqft)

In [73]:
def convert_area(value):
    if pd.isna(value):
        return np.nan

    value = str(value).lower().strip()

    value = value.replace(",", "")

    if "sqm" in value:
        value = (
            value.replace("sqm", "")
                 .replace("(", "")
                 .replace(")", "")
                 .strip()
        )
        return float(value) * 10.7639

    elif "sqft" in value:
        value = (
            value.replace("sqft", "")
                 .replace("(", "")
                 .replace(")", "")
                 .strip()
        )
        return float(value)

    elif "/" in value:
        value = value.replace("/", "").strip()
        return float(value)

    try:
        return float(value)

    except ValueError:
        return np.nan


df["area"] = df["area"].apply(convert_area)


df["area"] = df["area"].apply(convert_area)

In [74]:
def convert_area_unit(value):
    if pd.isna(value):
        return np.nan

    value = str(value).lower().strip()

    value = (
        value.replace(",", "")
             .replace("(", "")
             .replace(")", "")
             .strip()
    )

    if "sqm" in value:
        value = value.replace("sqm", "").strip()
        return float(value) * 10.7639

    elif "sqft" in value:
        value = value.replace("sqft", "").strip()
        return float(value)

    try:
        return float(value)

    except ValueError:
        return np.nan


df["area_unit"] = df["area_unit"].apply(convert_area_unit)

In [79]:
df.head(50)

,title,property_name,location,price,price_per_sqft,area,area_unit,area_type,bhk,bathrooms,possession,highlights,description,builder,posted_by
4,"2 BHK Flat in Chandivali, Mumbai","2 BHK Flat in Chandivali, Mumbai","Chandivali, Mumbai",23500000.0,37183.0,632.00,635.0701,Carpet Area,2 BHK,2.0,Ready To Move,8th out of 15 Floors | Centrally Air Conditioned,This well-Designed 2 bhk apartment in godrej u...,Owner,Yesterday
5,"2 BHK Flat in Powai, Mumbai","2 BHK Flat in Powai, Mumbai","Powai, Mumbai",26000000.0,39039.0,666.00,667.3618,Carpet Area,2 BHK,2.0,Ready To Move,10th out of 24 Floors | Centrally Air Conditioned,This north-East facing 2 bhk at kanakia future...,Owner,Yesterday
7,"3 BHK Flat in Chandivali, Mumbai","3 BHK Flat in Chandivali, Mumbai","Chandivali, Mumbai",37300000.0,34601.0,1078.00,1076.3900,Built-up Area,3 BHK,2.0,Ready To Move,7th out of 22 Floors | 1 Covered Parking,Located in the sought-After tulipia building a...,Owner,4w ago
8,"1 BHK Flat in Hiranandani Gardens Powai, Mumbai","1 BHK Flat in Hiranandani Gardens Powai, Mumbai","Hiranandani Gardens Powai, Mumbai",19000000.0,50131.0,379.00,376.7365,Carpet Area,1 BHK,1.0,Ready To Move,3rd out of 23 Floors | 1 Covered Parking,This north-West facing 1 bhk at regent hill of...,Owner,3w ago
9,"2 BHK Flat in Powai, Mumbai","2 BHK Flat in Powai, Mumbai","Powai, Mumbai",19000000.0,18446.0,1030.00,1033.3344,Super Built-up Area,2 BHK,2.0,Ready To Move,4th out of 17 Floors | Overlooking Park,This property faces the east direction. Contai...,Durga Estate Agency,<NA>
11,"2 BHK Flat in Powai, Mumbai","2 BHK Flat in Powai, Mumbai","Powai, Mumbai",23900000.0,25157.0,950.00,947.2232,Built-up Area,2 BHK,2.0,Ready To Move,6th out of 9 Floors | Overlooking Main Road,The flat is north-East-Facing. The society bui...,Owner,2mo ago
12,"2 BHK Flat in Hiranandani Gardens Powai, Mumbai","2 BHK Flat in Hiranandani Gardens Powai, Mumbai","Hiranandani Gardens Powai, Mumbai",18200000.0,19157.0,950.00,947.2232,Built-up Area,2 BHK,2.0,Ready To Move,3rd out of 18 Floors | Recently Renovated,This is a south-West-Facing property. Containi...,Property Anytime,Dealer
13,"2 BHK Flat in Chandivali, Mumbai","2 BHK Flat in Chandivali, Mumbai","Chandivali, Mumbai",24000000.0,20000.0,1200.00,1194.7929,Built-up Area,2 BHK,2.0,Ready To Move,14th out of 22 Floors | North-East Facing,This property faces the north-East direction. ...,RK Realtor,Dealer
15,"3 BHK Flat in Chandivali, Mumbai","3 BHK Flat in Chandivali, Mumbai","Chandivali, Mumbai",37300000.0,34601.0,1078.00,1076.3900,Carpet Area,3 BHK,2.0,Ready To Move,7th out of 21 Floors | 1 Covered Parking,The flat is over 1078 sq.Ft. Carpet area and c...,Owner,1mo ago
16,"1 BHK Flat in Chandivali, Mumbai","1 BHK Flat in Chandivali, Mumbai","Chandivali, Mumbai",14200000.0,23278.0,610.00,613.5423,Super Built-up Area,1 BHK,1.0,Ready To Move,8th out of 10 Floors | Overlooking Park,The flat is facing the south direction. The fl...,gansairaj property,Dealer
18,Studio Apartments / 1 RK Flats in Sangharsh Na...,Studio Apartments / 1 RK Flats in Sangharsh Na...,"Sangharsh Nagar, Chandivali",5000000.0,16666.0,300.00,301.3892,Carpet Area,1 BHK,1.0,Ready To Move,Close to Metro Station | Close to Hospital,Road facing area with very good ventilation as...,Owner,2w ago
19,"3 BHK Flat in Chandivali, Mumbai","3 BHK Flat in Chandivali, Mumbai","Chandivali, Mumbai",26500000.0,22844.0,1160.00,1162.5012,Super Built-up Area,3 BHK,3.0,Ready To Move,3rd out of 21 Floors | Overlooking Park,This property faces the east direction. The fl...,Minerva Properties,<NA>
20,"2 BHK Flat in Hiranandani Gardens Powai, Mumbai","2 BHK Flat in Hiranandani Gardens Powai, Mumbai","Hiranandani Gardens Powai, Mumbai",32500000.0,39537.0,822.00,818.0564,Carpet Area,2 BHK,2.0,Ready To Move,15th out of 30 Floors | Overlooking Park,The flat is facing the east direction. The fla...,Zen Realtors,Dealer
22,"2 BHK Flat in Chandivali, Mumbai","2 BHK Flat in Chandivali, Mumbai","Chandivali, Mumbai",26600000.0,38000.0,700.00,699.6535,Carpet Area,2 BHK,2.0,Ready To Move,11th out of 22 Floors | Overlooking Park,This residential flat is east-Facing direction...,Harvest Star India Realtors,Dealer
23,"2 BHK Flat in Chandivali, Mumbai","2 BHK Flat in Chandivali, Mumbai","Chandivali, Mumbai",24000000.0,35771.0,670.92,667.3618,Carpet Area,2 BHK,NaN,Ready To Move,10th out of 20 Floors | Overlooking Park,The residential building has 20 floors in tota...,Harvest Star India Realtors,Dealer
24,"2 BHK Flat in Raheja Vihar, Chandivali","2 BHK Flat in Raheja Vihar, Chandivali","Raheja Vihar, Chandivali",27500000.0,22916.0,1200.00,1194.7929,Super Built-up Area,2 BHK,2.0,Ready To Move,15th out of 20 Floors | Overlooking Park,The floor plan additionally contains 2.5 bedro...,VN Property,Dealer
25,"2 BHK Flat in Chandivali, Mumbai","2 BHK Flat in Chandivali, Mumbai","Chandivali, Mumbai",28500000.0,40714.0,700.00,699.6535,Carpet Area,2 BHK,2.0,Ready To Move,12th out of 21 Floors | Overlooking Park,The flat is east-Facing. The flat is over 700 ...,Saimaitri Enterprises,Dealer
26,"2 BHK Flat in Powai, Mumbai","2 BHK Flat in Powai, Mumbai","Powai, Mumbai",30500000.0,39559.0,771.00,1248.6124,Carpet Area,2 BHK,2.0,Ready To Move,19th out of 24 Floors | Overlooking Park,The flat is east-Facing. The flat occupies a b...,Propertism,<NA>
28,"2 BHK Flat in Chandivali, Mumbai","2 BHK Flat in Chandivali, Mumbai","Chandivali, Mumbai",22300000.0,33283.0,670.00,667.3618,Carpet Area,2 BHK,2.0,Ready To Move,17th out of 22 Floors,This north-West-Facing 2 bhk at vicinia offers...,Owner,1mo ago
29,"2 BHK Flat in Powai, Mumbai","2 BHK Flat in Powai, Mumbai","Powai, Mumbai",33500000.0,47925.0,699.00,699.6535,Carpet Area,2 BHK,2.0,Ready To Move,20th out of 26 Floors,Available 2 bhk 700 carpet with 2 balcony in e...,Golden Key Realty,Dealer
30,"3 BHK Flat in Chandivali, Mumbai","3 BHK Flat in Chandivali, Mumbai","Chandivali, Mumbai",32000000.0,32520.0,984.00,979.5149,Carpet Area,3 BHK,3.0,Ready To Move,5th out of 16 Floors | Overlooking Park,Check out this 3 bhk apartment for sale in mah...,Owner,2mo ago
31,"2 BHK Flat in Chandivali, Mumbai","2 BHK Flat in Chandivali, Mumbai","Chandivali, Mumbai",23500000.0,29375.0,800.00,796.5286,Built-up Area,2 BHK,2.0,Ready To Move,15th out of 17 Floors | Overlooking Park,A bright north-Exit 2bhk home in synchronicity...,Owner,1mo ago
32,"2 BHK Flat in Powai, Mumbai","2 BHK Flat in Powai, Mumbai","Powai, Mumbai",31000000.0,44915.0,690.19,688.8896,Carpet Area,2 BHK,2.0,Ready To Move,14th out of 26 Floors,The flat is facing the east direction. The flo...,Rm enterprises,<NA>
34,"2 BHK Flat in Powai, Mumbai","2 BHK Flat in Powai, Mumbai","Powai, Mumbai",23000000.0,24210.0,950.00,947.2232,Built-up Area,2 BHK,2.0,Ready To Move,2nd out of 24 Floors | Overlooking Park,This is a east-Facing property. Constructed on...,Propertism,<NA>
35,"2 BHK Flat in Raheja Vihar, Chandivali","2 BHK Flat in Raheja Vihar, Chandivali","Raheja Vihar, Chandivali",29000000.0,38512.0,753.00,753.4730,Carpet Area,2 BHK,2.0,Ready To Move,16th out of 20 Floors | Overlooking Park,Experience luxury living in one of powais most...,BRICKS AND BOND REALTY,<NA>
36,"2 BHK Flat in Powai, Mumbai","2 BHK Flat in Powai, Mumbai","Powai, Mumbai",32500000.0,52419.0,620.00,624.3062,Carpet Area,2 BHK,2.0,Ready To Move,18th out of 23 Floors | Private Garden,The flat is facing the west direction. The fla...,VIDYANT PROPERTY,<NA>
37,"2 BHK Flat in Powai, Mumbai","2 BHK Flat in Powai, Mumbai","Powai, Mumbai",31000000.0,51839.0,598.00,602.7784,Carpet Area,2 BHK,2.0,Ready To Move,6th out of 23 Floors | Overlooking Park,This residential flat is east-Facing direction...,AB Properties,<NA>
38,"1 BHK Flat in Chandivali, Mumbai","1 BHK Flat in Chandivali, Mumbai","Chandivali, Mumbai",17500000.0,29166.0,600.00,602.7784,Built-up Area,1 BHK,2.0,Ready To Move,5th out of 15 Floors | Vaastu Compliant,This is your chance to a 1 bhk apartment flat ...,Owner,1mo ago
39,"2 BHK Flat in Powai, Mumbai","2 BHK Flat in Powai, Mumbai","Powai, Mumbai",30000000.0,38461.0,780.00,775.0008,Built-up Area,2 BHK,2.0,Ready To Move,2nd out of 23 Floors | Overlooking Main Road,The flat is facing the north-East direction. C...,RK Realtor,Dealer
40,"2 BHK Flat in Powai, Mumbai","2 BHK Flat in Powai, Mumbai","Powai, Mumbai",28500000.0,43313.0,658.00,656.5979,Carpet Area,2 BHK,2.0,Ready To Move,16th out of 26 Floors | Overlooking Park,Unused premium apartment available for sale in...,Sky Haven Estate,Dealer
41,"3 BHK Flat in Lok Milan Colony, Chandivali","3 BHK Flat in Lok Milan Colony, Chandivali","Lok Milan Colony, Chandivali",33000000.0,22916.0,1440.00,1442.3626,Built-up Area,3 BHK,3.0,Ready To Move,4th out of 17 Floors | Overlooking Park,"3 bhk flat for rent in synchronicity, chandiva...",Global Realtors,<NA>
42,"3 BHK Flat in Chandivali, Mumbai","3 BHK Flat in Chandivali, Mumbai","Chandivali, Mumbai",28500000.0,35315.0,807.00,807.2925,Carpet Area,3 BHK,3.0,Ready To Move,8th out of 18 Floors,Available 3 bhk flat for sale in amryllis buil...,Global Realtors,<NA>
43,"2 BHK Flat in Raheja Vihar, Chandivali","2 BHK Flat in Raheja Vihar, Chandivali","Raheja Vihar, Chandivali",28900000.0,25130.0,1150.00,1151.7373,Super Built-up Area,2 BHK,2.0,Ready To Move,16th out of 20 Floors | Overlooking Park,Experience luxury living in one of powais most...,THE JANGID BROTHERS,<NA>
44,"2 BHK Flat in Hiranandani Gardens Powai, Mumbai","2 BHK Flat in Hiranandani Gardens Powai, Mumbai","Hiranandani Gardens Powai, Mumbai",31000000.0,41005.0,756.00,979.5149,Carpet Area,2 BHK,2.0,Ready To Move,18th out of 24 Floors | Overlooking Park,Kanakia silicon valley is a premium residentia...,Homes For All Real Estate Private Limited,<NA>
45,"1 BHK Flat in Hiranandani Gardens Powai, Mumbai","1 BHK Flat in Hiranandani Gardens Powai, Mumbai","Hiranandani Gardens Powai, Mumbai",19500000.0,51315.0,380.00,602.7784,Carpet Area,1 BHK,1.0,Ready To Move,20th out of 23 Floors,Fully furnished 1 bhk apartment available for ...,UPGRADE REALTY,Dealer
46,"1 BHK Flat in Chandivali, Mumbai","1 BHK Flat in Chandivali, Mumbai","Chandivali, Mumbai",14300000.0,32352.0,442.00,441.3199,Carpet Area,1 BHK,2.0,Ready To Move,3rd out of 14 Floors,The flat is east-Facing. The flat occupies a c...,Anchor Realtors,Dealer
48,"2 BHK Flat in Powai, Mumbai","2 BHK Flat in Powai, Mumbai","Powai, Mumbai",24700000.0,30232.0,817.00,818.0564,Carpet Area,2 BHK,2.0,Ready To Move,2nd out of 23 Floors | Private Garden,"This spacious 2 bhk at lake pleasant, powai of...",Owner,2mo ago
49,"1 BHK Flat in Hiranandani Gardens Powai, Mumbai","1 BHK Flat in Hiranandani Gardens Powai, Mumbai","Hiranandani Gardens Powai, Mumbai",19000000.0,50131.0,379.00,548.9589,Carpet Area,1 BHK,2.0,Ready To Move,5th out of 25 Floors | Overlooking Park,This residential flat is north-East-Facing dir...,Sanjay Sawant,Dealer
50,"3 BHK Flat in Powai, Mumbai","3 BHK Flat in Powai, Mumbai","Powai, Mumbai",39000000.0,26000.0,1500.00,1496.1821,Built-up Area,3 BHK,3.0,Ready To Move,15th out of 21 Floors | Overlooking Park,Presenting a spacious and well-Maintained 3 bh...,Sky Haven Estate,Dealer
51,"2 BHK Flat in Hiranandani Gardens Powai, Mumbai","2 BHK Flat in Hiranandani Gardens Powai, Mumbai","Hiranandani Gardens Powai, Mumbai",38500000.0,49935.0,771.00,1248.6124,Carpet Area,2 BHK,2.0,Ready To Move,7th out of 27 Floors | Overlooking Park,This is a east-Facing property. The flat is ov...,SAHYADRI REAL ESTATE ADVISORY,<NA>
52,"2 BHK Flat in Hiranandani Gardens Powai, Mumbai","2 BHK Flat in Hiranandani Gardens Powai, Mumbai","Hiranandani Gardens Powai, Mumbai",40000000.0,31872.0,1255.00,1259.3763,Super Built-up Area,2 BHK,2.0,Ready To Move,2nd out of 22 Floors | Overlooking Park,"Spread across a super built-Up area of 1,025 s...",Durga Estate Agency,<NA>
53,"3 BHK Flat in Powai, Mumbai","3 BHK Flat in Powai, Mumbai","Powai, Mumbai",41000000.0,26451.0,1550.00,1550.0016,Super Built-up Area,3 BHK,3.0,Ready To Move,6th out of 22 Floors | Overlooking Park,The flat is facing the east direction. Contain...,Durga Estate Agency,<NA>
54,"3 BHK Flat in Powai, Mumbai","3 BHK Flat in Powai, Mumbai","Powai, Mumbai",40500000.0,27000.0,1500.00,1496.1821,Super Built-up Area,3 BHK,3.0,Ready To Move,6th out of 22 Floors | Overlooking Park,This property faces the east direction. The fl...,Durga Estate Agency,<NA>
55,"1 BHK Flat in Hiranandani Gardens Powai, Mumbai","1 BHK Flat in Hiranandani Gardens Powai, Mumbai","Hiranandani Gardens Powai, Mumbai",19900000.0,52506.0,379.00,376.7365,Carpet Area,1 BHK,1.0,Ready To Move,19th out of 23 Floors | Overlooking Park,A well-Designed 1 bhk apartment in regent hill...,Owner,2mo ago
56,"1 BHK Flat in Hiranandani Gardens Powai, Mumbai","1 BHK Flat in Hiranandani Gardens Powai, Mumbai","Hiranandani Gardens Powai, Mumbai",19200000.0,50659.0,379.00,376.7365,Carpet Area,1 BHK,2.0,Ready To Move,4th out of 25 Floors | Overlooking Park,The flat is facing the north-East direction. T...,GANGA REALTORS,Dealer
57,"2 BHK Flat in Powai, Mumbai","2 BHK Flat in Powai, Mumbai","Powai, Mumbai",39000000.0,32500.0,1200.00,1194.7929,Super Built-up Area,2 BHK,2.0,Ready To Move,11th out of 27 Floors | Overlooking Park,The flat is east-Facing. The flat occupies a s...,MANASVI PROPERTIES,<NA>
58,"3 BHK Flat in Powai, Mumbai","3 BHK Flat in Powai, Mumbai","Powai, Mumbai",39200000.0,32666.0,1200.00,1194.7929,Super Built-up Area,3 BHK,2.0,Ready To Move,11th out of 27 Floors | Overlooking Park,This residential flat is east-Facing direction...,MANASVI PROPERTIES,<NA>
59,"3 BHK Flat in Chandivali, Mumbai","3 BHK Flat in Chandivali, Mumbai","Chandivali, Mumbai",42400000.0,34754.0,1220.00,1216.3207,Carpet Area,3 BHK,3.0,Ready To Move,10th out of 12 Floors,"Constructed on a carpet area of 1220 sq.Ft., t...",Harvest Star India Realtors,Dealer
60,"2 BHK Flat in Hiranandani Gardens Powai, Mumbai","2 BHK Flat in Hiranandani Gardens Powai, Mumbai","Hiranandani Gardens Powai, Mumbai",39000000.0,36448.0,1070.00,1065.6261,Super Built-up Area,2 BHK,2.0,Ready To Move,8th out of 33 Floors | Overlooking Park,The flat is facing the north direction. Constr...,Property Anytime,Dealer
61,"3 BHK Flat in Hiranandani Gardens Powai, Mumbai","3 BHK Flat in Hiranandani Gardens Powai, Mumbai","Hiranandani Gardens Powai, Mumbai",40000000.0,34782.0,1150.00,1151.7373,Built-up Area,3 BHK,3.0,Ready To Move,3rd out of 7 Floors | Overlooking Park,The flat is facing the east direction. The fla...,Sanjay Sawant,Dealer